# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1236edf6bed4ee531f5ee9337614ff1cc7867ecd833584dbad3a0e9eb1f020c7da0890d5e47cd99cbf875fa01374c3c78435592266dfcaa2de3baa0e39956700

test:
  secret_key_base: 6c53996ade80081a8f522568e03d55b9002b22dd541c6613baef15e820a2c62d283889ce6c502b357a57bd2c6447cad22310722c39b1d5b94b27d9dc4cc126db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
